/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rezini.crono.views.produto;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rezini.crono.dao.ProdutoDao;
import rezini.crono.model.Produto;

/**
 *
 * @author ivan rezini
 */
public class PanelCadastroProduto extends javax.swing.JPanel {

    private CardLayout cl;

    /**
     * Creates new form PanelCadastroProduto
     */
    public PanelCadastroProduto() {
        initComponents();
        this.cl = (CardLayout) this.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoDescricao = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CADASTRO DE NOVO PRODUTO");
        add(jLabelTitulo);
        jLabelTitulo.setBounds(0, 10, 470, 22);

        jLabelNome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNome.setText("Nome:");
        add(jLabelNome);
        jLabelNome.setBounds(20, 60, 70, 20);

        jLabelDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDesc.setText("Descrição:");
        add(jLabelDesc);
        jLabelDesc.setBounds(10, 100, 100, 30);

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        add(campoNome);
        campoNome.setBounds(80, 50, 210, 30);
        add(campoDescricao);
        campoDescricao.setBounds(80, 100, 310, 30);

        jButtonCancelar.setBackground(new java.awt.Color(255, 51, 0));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        add(jButtonCancelar);
        jButtonCancelar.setBounds(270, 270, 85, 30);

        jButtonSalvar.setBackground(new java.awt.Color(0, 255, 51));
        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });
        add(jButtonSalvar);
        jButtonSalvar.setBounds(370, 270, 80, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
       
    }//GEN-LAST:event_campoNomeActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampos();

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
    if (validarCampos()) {
            Produto pro = new Produto();
            pro.setNomeProduto(campoNome.getText());
            pro.setDescProduto(campoDescricao.getText());

            ProdutoDao proDao = new ProdutoDao();
            try {
                proDao.inserir(pro);
                 JOptionPane.showMessageDialog(null, "Cadastro de produto salvo com susesso");
                 limparCampos();
            } catch (SQLException ex) {
                Logger.getLogger(PanelCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
                 JOptionPane.showMessageDialog(null, "Falha no cadastro ");
            }
        }
    }//GEN-LAST:event_jButtonSalvarMouseClicked
    private boolean validarCampos() {
        String nome = campoNome.getText();
        if (nome.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe um nome");
            return false;
        }
        String desc = campoDescricao.getText();
        if (desc.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe uma Descrição");
            return false;
        } else {
            return true;
        }
    }

    private void limparCampos() {
        campoNome.setText(null);
        campoDescricao.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoNome;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
