/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rezini.crono.views.operacao;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import rezini.crono.dao.OperacaoDao;
import rezini.crono.dao.ProdutoDao;
import rezini.crono.model.Operacao;
import rezini.crono.model.Produto;

/**
 *
 * @author ivan rezini
 */
public class PanelCadastroOperacao extends javax.swing.JPanel {

    /**
     * Creates new form PanelCadastroOperacao
     *
     * @throws java.sql.SQLException
     */
    public PanelCadastroOperacao() throws SQLException {
        initComponents();

        ProdutoDao produto = new ProdutoDao();

        List<Produto> lista = produto.listaProdutos();
        ArrayList li = new ArrayList();
        for (int i = 0; i < lista.size(); i++) {
            Produto p = lista.get(i);
            li.add(p.getProdutoMenu());
        }
        for (int i = 0; i < li.size(); i++) {
            this.jMenuProduto.addItem((String) li.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelProduto = new javax.swing.JLabel();
        jMenuProduto = new javax.swing.JComboBox<>();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelOperacao = new javax.swing.JLabel();
        jTextOperacao = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jTextDescricao = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Cadastro de operaçoes");

        jLabelProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelProduto.setText("Produto:");

        jMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdutoActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 51, 0));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonSalvar.setBackground(new java.awt.Color(0, 255, 51));
        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });

        jLabelOperacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelOperacao.setText("Operação:");

        jLabelDescricao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelDescricao.setText("Descriçao:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMenuProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDescricao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextOperacao)
                                    .addComponent(jTextDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProduto)
                            .addComponent(jMenuProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelOperacao)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescricao)
                    .addComponent(jTextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdutoActionPerformed
    }//GEN-LAST:event_jMenuProdutoActionPerformed

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalvarMouseClicked
        if (validarCampos()) {
            Operacao op = new Operacao();
            op.setNomeOperacao(jTextOperacao.getText());
            op.setDescOperacao(jTextDescricao.getText());
            String produto = jMenuProduto.getSelectedItem().toString();
            produto = produto.replaceAll("[^0-9]", "");
            int cod = Integer.parseInt(produto);
            op.setCodProduto(cod);
            op.setStatusOperacao(1); //criaçãode operacao nova prametro "1" indica que não possui elementos cadastrados
            OperacaoDao opDao = new OperacaoDao();

            try {
                opDao.inserir(op);
                JOptionPane.showMessageDialog(null, "Cadastro de produto salvo com susesso");
                limparCampos();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Falha no cadastro ");
            }
        }


    }//GEN-LAST:event_jButtonSalvarMouseClicked
    private boolean validarCampos() {
        String nome = jTextOperacao.getText();
        if (nome.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe uma operaçao");
            return false;
        }
        String desc = jTextDescricao.getText();
        if (desc.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe uma Descrição");
            return false;
        } else {
            return true;
        }
    }

    private void limparCampos() {
        jTextOperacao.setText(null);
        jTextDescricao.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelOperacao;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JComboBox<String> jMenuProduto;
    private javax.swing.JTextField jTextDescricao;
    private javax.swing.JTextField jTextOperacao;
    // End of variables declaration//GEN-END:variables
}
