/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rezini.crono.views.tomadatempo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author ivan rezini
 */
public class PanelTomadaDeTempo extends javax.swing.JPanel {

     private Timer timer;  
    private int currentSegundo = 0;
    private int currentMinuto = 0;
    private int currentHora = 0;
    private int velocidade = 1000;

    /**
     * Creates new form PanelTomadaDeTempo
     */
    public PanelTomadaDeTempo() {
        initComponents();
        iniciarCintagem();
        stopTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTomadaDeTempo = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelListaOperacao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaOperacao = new javax.swing.JTable();
        jLabelTitulo1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jButton1.setText("inicio");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("pare");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTomadaDeTempoLayout = new javax.swing.GroupLayout(jPanelTomadaDeTempo);
        jPanelTomadaDeTempo.setLayout(jPanelTomadaDeTempoLayout);
        jPanelTomadaDeTempoLayout.setHorizontalGroup(
            jPanelTomadaDeTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTomadaDeTempoLayout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addGroup(jPanelTomadaDeTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTomadaDeTempoLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanelTomadaDeTempoLayout.setVerticalGroup(
            jPanelTomadaDeTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTomadaDeTempoLayout.createSequentialGroup()
                .addGap(0, 340, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanelTomadaDeTempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)))
        );

        add(jPanelTomadaDeTempo, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        add(jPanel1, "card3");

        jPanelListaOperacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        jTableListaOperacao.setBorder(new javax.swing.border.MatteBorder(null));
        jTableListaOperacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Produto", "Descrição"
            }
        ));
        jTableListaOperacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaOperacaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaOperacao);

        jLabelTitulo1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("LISTA DE OPERAÇÕES COM ELEMENTOS");

        javax.swing.GroupLayout jPanelListaOperacaoLayout = new javax.swing.GroupLayout(jPanelListaOperacao);
        jPanelListaOperacao.setLayout(jPanelListaOperacaoLayout);
        jPanelListaOperacaoLayout.setHorizontalGroup(
            jPanelListaOperacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelListaOperacaoLayout.setVerticalGroup(
            jPanelListaOperacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListaOperacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
        );

        add(jPanelListaOperacao, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        iniciarCintagem();

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        stopTime();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTableListaOperacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaOperacaoMouseClicked

        int linha = jTableListaOperacao.getSelectedRow();
        String operacao = jTableListaOperacao.getValueAt(linha, 1).toString();
        String descricao = jTableListaOperacao.getValueAt(linha, 3).toString();
        String codigo = jTableListaOperacao.getValueAt(linha, 0).toString();
        int cod = Integer.parseInt(codigo);

       /* jLabelInsertDescricao.setText(descricao);
        jLabelInsertOperacao.setText(operacao);
        this.add(jPanelListaElementos, "lista");
        this.cl.show(this, "lista");
        try {
            this.popularTabelaElemento(cod);
        } catch (SQLException ex) {
            Logger.getLogger(PanelListaDeElemento.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jTableListaOperacaoMouseClicked
    //metodo que recebe o tempo q o microondas vai aquecer o alimento

  private void iniciarCintagem() {
        ActionListener action = (ActionEvent e) -> {
            currentSegundo++;
            
            if(currentSegundo==60){
                currentMinuto++;
                currentSegundo = 0;
            }
            
            if(currentMinuto==60){
                currentHora++;
                currentMinuto = 0;
            }
            
            String hr = currentHora <= 9? "0"+currentHora:currentHora+"";
            String min = currentMinuto <= 9? "0"+currentMinuto:currentMinuto+"";
            String seg = currentSegundo <= 9? "0"+currentSegundo:currentSegundo+"";
            
            label.setText(hr+":"+min+":"+seg);  
        };  
        this.timer = new Timer(velocidade, action);  
        this.timer.start();
    }


private void stopTime() {
        timer.stop();
        currentHora = 0;
        currentMinuto = 0;
        currentSegundo = 0;
        label.setText("00:00:00");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelListaOperacao;
    private javax.swing.JPanel jPanelTomadaDeTempo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaOperacao;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
///https://pt.stackoverflow.com/questions/396127/java-cronometro-sem-swing-timer-e-com-mvc
//http://procode-java.blogspot.com/2014/07/fato-criando-um-cronometro-em-java.html